name: Parallel jobs
on: push
jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "First job done"
  second:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Second job done"
  third:
    runs-on: ubuntu-latest
    steps:
      - run: sleep 10 && echo "Third job done"
